In [2]:
import pandas as pd

In [3]:
df = pd.read_excel("UserReviewsClean43LIWC.xlsx")

df.head()

,url,idvscore,reviewer,dateP,Rev,thumbsUp,thumbsTot,WC,Analytic,Clout,...,Comma,Colon,SemiC,QMark,Exclam,Dash,Quote,Apostro,Parenth,OtherP
0,https://www.metacritic.com/movie/bronson,8,'Longbottom94',"'Apr 25, 2013'",'Many have dismissed this film for not explor...,2,2,113,94.05,32.91,...,4.42,0.0,0.0,0.0,0.0,0.88,0,1.77,0.00,0.0
1,https://www.metacritic.com/movie/bronson,9,'MartinB',"'Oct 13, 2009'",'Anyone who doesn t like this movie simply ju...,0,1,103,57.11,38.53,...,0.97,0.0,0.0,0.0,0.0,0.00,0,1.94,5.83,0.0
2,https://www.metacritic.com/movie/bronson,10,'Jaakko',"'Jul 19, 2012'",'Not sure what to think at this film at first...,1,1,143,75.73,66.27,...,0.70,0.0,0.0,0.0,0.0,0.00,0,1.40,0.00,1.4
3,https://www.metacritic.com/movie/bronson,6,'CapoR',"'Oct 13, 2009'",'Nicely portrayed but it lacks the elements t...,0,1,14,83.81,23.75,...,0.00,0.0,0.0,0.0,0.0,0.00,0,14.29,0.00,0.0
4,https://www.metacritic.com/movie/bronson,8,'OrwellB.',"'Oct 10, 2009'",'Bronson is more than entertainment. It is ar...,0,0,20,93.26,69.14,...,0.00,0.0,0.0,0.0,0.0,0.00,0,10.00,0.00,0.0

In [4]:
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 319662 entries, 0 to 319661
Data columns (total 100 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   url           319662 non-null  str
 1   idvscore      316258 non-null  object
 2   reviewer      316255 non-null  str
 3   dateP         316249 non-null  str
 4   Rev           316249 non-null  str
 5   thumbsUp      316082 non-null  object
 6   thumbsTot     316086 non-null  object
 7   WC            319662 non-null  int64
 8   Analytic      319662 non-null  float64
 9   Clout         319662 non-null  float64
 10  Authentic     319662 non-null  float64
 11  Tone          319662 non-null  float64
 12  WPS           319662 non-null  float64
 13  Sixltr        319662 non-null  float64
 14  Dic           319662 non-null  float64
 15  function      319662 non-null  float64
 16  pronoun       319662 non-null  float64
 17  ppron         319662 non-null  float64
 18  i             319662 non-null  float64
 19  we            319662 non-null  float64
 20  you           319662 non-null  float64
 21  shehe         319662 non-null  float64
 22  they          319662 non-null  float64
 23  ipron         319662 non-null  float64
 24  article       319662 non-null  float64
 25  prep          319662 non-null  float64
 26  auxverb       319662 non-null  float64
 27  adverb        319662 non-null  float64
 28  conj          319662 non-null  float64
 29  negate        319662 non-null  float64
 30  verb          319662 non-null  float64
 31  adj           319662 non-null  float64
 32  compare       319662 non-null  float64
 33  interrog      319662 non-null  float64
 34  number        319662 non-null  float64
 35  quant         319662 non-null  float64
 36  affect        319662 non-null  float64
 37  posemo        319662 non-null  float64
 38  negemo        319662 non-null  float64
 39  anx           319662 non-null  float64
 40  anger         319662 non-null  float64
 41  sad           319662 non-null  float64
 42  social        319662 non-null  float64
 43  family        319662 non-null  float64
 44  friend        319662 non-null  float64
 45  female        319662 non-null  float64
 46  male          319662 non-null  float64
 47  cogproc       319662 non-null  float64
 48  insight       319662 non-null  float64
 49  cause         319662 non-null  float64
 50  discrep       319662 non-null  float64
 51  tentat        319662 non-null  float64
 52  certain       319662 non-null  float64
 53  differ        319662 non-null  float64
 54  percept       319662 non-null  float64
 55  see           319662 non-null  float64
 56  hear          319662 non-null  float64
 57  feel          319662 non-null  float64
 58  bio           319662 non-null  float64
 59  body          319662 non-null  float64
 60  health        319662 non-null  float64
 61  sexual        319662 non-null  float64
 62  ingest        319662 non-null  float64
 63  drives        319662 non-null  float64
 64  affiliation   319662 non-null  float64
 65  achieve       319662 non-null  float64
 66  power         319662 non-null  float64
 67  reward        319662 non-null  float64
 68  risk          319662 non-null  float64
 69  focuspast     319662 non-null  float64
 70  focuspresent  319662 non-null  float64
 71  focusfuture   319662 non-null  float64
 72  relativ       319662 non-null  float64
 73  motion        319662 non-null  float64
 74  space         319662 non-null  float64
 75  time          319662 non-null  float64
 76  work          319662 non-null  float64
 77  leisure       319662 non-null  float64
 78  home          319662 non-null  float64
 79  money         319662 non-null  float64
 80  relig         319662 non-null  float64
 81  death         319662 non-null  float64
 82  informal      319662 non-null  float64
 83  swear         319662 non-null  float64
 84  netspeak      319662 non-null  float64
 85  assent        319662 non-null  float64
 86  nonflu        319662 non-null  float64
 87  filler        319662 non-null  float64
 88  AllPunc       319662 non-null  float64
 89  Period        319662 non-null  float64
 90  Comma         319662 non-null  float64
 91  Colon         319662 non-null  float64
 92  SemiC         319662 non-null  float64
 93  QMark         319662 non-null  float64
 94  Exclam        319662 non-null  float64
 95  Dash          319662 non-null  float64
 96  Quote         319662 non-null  int64
 97  Apostro       319662 non-null  float64
 98  Parenth       319662 non-null  float64
 99  OtherP        319662 non-null  float64
dtypes: float64(91), int64(2), object(3), str(4)
memory usage: 243.9+ MB

url            0
idvscore    3404
reviewer    3407
dateP       3413
Rev         3413
            ...
Dash           0
Quote          0
Apostro        0
Parenth        0
OtherP         0
Length: 100, dtype: int64

In [5]:
df['reviewer'].unique

<bound method Series.unique of 0             'Longbottom94'
1                  'MartinB'
2                   'Jaakko'
3                    'CapoR'
4                 'OrwellB.'
                 ...
319657             'Zenflar'
319658      'juiliopaublito'
319659     'PorridgeBoy3000'
319660          'jamesfhall'
319661            'Motoritz'
Name: reviewer, Length: 319662, dtype: str>

Here i took a look at the reviewers names, they all were in square brackets so now i'm gonna remove the square brackets and the extra space on the front

In [6]:
df['reviewer'] = df['reviewer'].str.strip(" '")
df['reviewer'].unique

<bound method Series.unique of 0            Longbottom94
1                 MartinB
2                  Jaakko
3                   CapoR
4                OrwellB.
               ...
319657            Zenflar
319658     juiliopaublito
319659    PorridgeBoy3000
319660         jamesfhall
319661           Motoritz
Name: reviewer, Length: 319662, dtype: str>

Now i removed all the square brackets. I also saw that for date and Rev there was the same issue, so now i'm gonna remove te square brackets and the extra space for those colomms too.

In [7]:
df['dateP'] = df['dateP'].str.strip(" '")
df['dateP'].unique

<bound method Series.unique of 0         Apr 25, 2013
1         Oct 13, 2009
2         Jul 19, 2012
3         Oct 13, 2009
4         Oct 10, 2009
              ...
319657     Sep 6, 2021
319658    Nov 25, 2021
319659    Dec 31, 2021
319660    Jan 20, 2022
319661     Feb 7, 2022
Name: dateP, Length: 319662, dtype: str>

In [8]:
df['Rev'] = df['Rev'].str.strip(" '")
df['Rev'].unique

<bound method Series.unique of 0         Many have dismissed this film for not explorin...
1         Anyone who doesn t like this movie simply just...
2         Not sure what to think at this film at first. ...
3         Nicely portrayed but it lacks the elements to ...
4         Bronson is more than entertainment. It is art ...
                                ...
319657    A+A+A+A+A+A+A+A+A+A+A+A+A+A+A+A+A+A+A+A+A+A+A+...
319658    in my opinion spirited away is one of the best...
319659    Usually I don t like watching movies that much...
319660    Studio Ghibli s gripping masterpiece Spirited ...
319661    Words cannot describe how amazing this movie i...
Name: Rev, Length: 319662, dtype: str>

Here you can see that i removed the square brackets from the reviews.

In [9]:
df.head()

,url,idvscore,reviewer,dateP,Rev,thumbsUp,thumbsTot,WC,Analytic,Clout,...,Comma,Colon,SemiC,QMark,Exclam,Dash,Quote,Apostro,Parenth,OtherP
0,https://www.metacritic.com/movie/bronson,8,Longbottom94,"Apr 25, 2013",Many have dismissed this film for not explorin...,2,2,113,94.05,32.91,...,4.42,0.0,0.0,0.0,0.0,0.88,0,1.77,0.00,0.0
1,https://www.metacritic.com/movie/bronson,9,MartinB,"Oct 13, 2009",Anyone who doesn t like this movie simply just...,0,1,103,57.11,38.53,...,0.97,0.0,0.0,0.0,0.0,0.00,0,1.94,5.83,0.0
2,https://www.metacritic.com/movie/bronson,10,Jaakko,"Jul 19, 2012",Not sure what to think at this film at first. ...,1,1,143,75.73,66.27,...,0.70,0.0,0.0,0.0,0.0,0.00,0,1.40,0.00,1.4
3,https://www.metacritic.com/movie/bronson,6,CapoR,"Oct 13, 2009",Nicely portrayed but it lacks the elements to ...,0,1,14,83.81,23.75,...,0.00,0.0,0.0,0.0,0.0,0.00,0,14.29,0.00,0.0
4,https://www.metacritic.com/movie/bronson,8,OrwellB.,"Oct 10, 2009",Bronson is more than entertainment. It is art ...,0,0,20,93.26,69.14,...,0.00,0.0,0.0,0.0,0.0,0.00,0,10.00,0.00,0.0

In [10]:
df.to_csv('UserReviews_cleaned.csv', index=False)