In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_excel("sales.xlsx")

df.head()

,year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,Unnamed: 8,opening_weekend,theatre_count,avg run per theatre,runtime,keywords,creative_type,url
0,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...
1,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,NaN,5486209.0,2433.0,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust
2,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos
3,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...
4,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,NaN,12177488.0,2411.0,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...

In [3]:
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 30612 entries, 0 to 30611
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   year                      30612 non-null  int64
 1   release_date              30612 non-null  str
 2   title                     30604 non-null  object
 3   genre                     28908 non-null  str
 4   international_box_office  21575 non-null  float64
 5   domestic_box_office       11884 non-null  float64
 6   worldwide_box_office      21575 non-null  float64
 7   production_budget         4480 non-null   float64
 8   Unnamed: 8                0 non-null      float64
 9   opening_weekend           10929 non-null  float64
 10  theatre_count             10963 non-null  float64
 11  avg run per theatre       10952 non-null  float64
 12  runtime                   24559 non-null  float64
 13  keywords                  12517 non-null  object
 14  creative_type             26667 non-null  str
 15  url                       30612 non-null  str
dtypes: float64(9), int64(1), object(2), str(4)
memory usage: 3.7+ MB

year                            0
release_date                    0
title                           8
genre                        1704
international_box_office     9037
domestic_box_office         18728
worldwide_box_office         9037
production_budget           26132
Unnamed: 8                  30612
opening_weekend             19683
theatre_count               19649
avg run per theatre         19660
runtime                      6053
keywords                    18095
creative_type                3945
url                             0
dtype: int64

In [4]:
df = df.drop(columns=['Unnamed: 8'])

In the overview I saw that the columm Unnamed: 8 had 0 non-null values, this is clearly an empty columm and therefore it can ben removed.

In [5]:
df['release_date'].unique()

<StringArray>
[             'January 1st',             'January 12th',
             'January 28th',          '2002 (Wide) by ',
             'January 25th',                'June 21st',
                 'May 10th',              'January 2nd',
                 'June 7th',             'January 18th',
 ...
           '2003 (Limited)',              '2002 (Wide)',
            '2020 (Wide) (',      '2020 (Canceled) by ',
 'Fall 2020 (Canceled) by ',          '2022 (Wide) by ',
            '2021 (Wide) (',                   'Summer',
      '2022 (Canceled) by ',      '2021 (Canceled) by ']
Length: 392, dtype: str

Here you can see that there is a widespread of versions that the release dat can have.

In [6]:
df['production_budget'].unique()

array([          nan, 3.0000000e+07, 1.1000000e+07, 2.2000000e+07,
       1.0000000e+07, 4.0000000e+07, 8.0000000e+05, 7.0000000e+07,
       3.4800000e+07, 5.0000000e+07, 1.3000000e+07, 1.0000000e+06,
       9.6000000e+06, 1.0000000e+08, 3.0600000e+08, 1.3500000e+08,
       6.0000000e+06, 1.0300000e+07, 9.0000000e+06, 4.5000000e+07,
       6.0000000e+07, 4.2000000e+07, 1.3000000e+08, 6.5000000e+05,
       7.8000000e+06, 3.5000000e+07, 1.2000000e+07, 8.5000000e+06,
       2.5000000e+07, 1.0200000e+08, 1.9800000e+07, 9.0000000e+07,
       1.5000000e+07, 6.8000000e+07, 1.5700000e+07, 2.6200000e+08,
       8.4000000e+07, 3.0000000e+05, 1.6000000e+08, 1.1100000e+08,
       4.0000000e+06, 1.9500000e+07, 4.5000000e+06, 2.0000000e+07,
       6.5000000e+07, 1.2500000e+08, 1.7500000e+08, 9.9000000e+07,
       7.0000000e+06, 4.6500000e+07, 4.8000000e+07, 2.3000000e+07,
       1.1000000e+08, 9.5000000e+06, 3.8000000e+07, 2.4000000e+07,
       2.0000000e+08, 3.6000000e+07, 1.5000000e+08, 1.2000000e+08,
       3.0000000e+08, 3.0000000e+06, 7.5000000e+07, 1.9000000e+07,
       1.6066830e+07, 5.0000000e+06, 5.5000000e+07, 3.5000000e+06,
       1.8000000e+07, 1.3290000e+08, 2.8000000e+07, 2.6700000e+07,
       2.6000000e+07, 6.4000000e+06, 1.0600000e+08, 2.7000000e+06,
       4.3000000e+07, 1.8000000e+08, 1.6000000e+07, 6.5000000e+06,
       3.7500000e+06, 1.6500000e+07, 1.7000000e+07, 4.7000000e+07,
       2.0000000e+06, 8.0000000e+06, 2.4000000e+06, 2.2500000e+07,
       1.2500000e+07, 3.8000000e+06, 1.6500000e+08, 1.4000000e+06,
       1.5000000e+06, 1.1600000e+08, 1.5800000e+07, 6.2000000e+07,
       2.1000000e+06, 5.5000000e+06, 3.2000000e+07, 1.7500000e+06,
       2.9000000e+07, 3.7000000e+07, 8.0000000e+07, 1.8500000e+08,
       7.7930000e+06, 7.5000000e+06, 1.0400000e+08, 5.0000000e+05,
       8.8000000e+07, 1.8750000e+08, 1.5600000e+08, 6.3000000e+07,
       2.1000000e+07, 1.1800000e+07, 5.2500000e+06, 2.5000000e+06,
       7.7500000e+07, 8.9000000e+06, 8.8000000e+05, 4.5500000e+07,
       3.1000000e+07, 3.3000000e+07, 1.1900000e+07, 5.1000000e+07,
       6.0000000e+05, 1.6800000e+05, 8.8000000e+06, 1.7800000e+08,
       3.4000000e+07, 4.2500000e+05, 4.5000000e+05, 2.9200000e+07,
       5.8000000e+07, 2.5000000e+05, 7.0000000e+05, 1.2500000e+06,
       9.0000000e+05, 6.6000000e+07, 7.7000000e+07, 1.0800000e+08,
       3.2000000e+06, 1.5200000e+08, 5.6000000e+05, 1.2000000e+06,
       1.2700000e+07, 1.0000000e+05, 5.3000000e+07, 2.2500000e+05,
       4.7500000e+07, 1.4400000e+08, 3.6000000e+06, 6.1000000e+07,
       1.7500000e+05, 1.0500000e+08, 1.1000000e+06, 9.5000000e+07,
       1.4000000e+08, 2.1700000e+08, 8.5000000e+05, 6.0000000e+04,
       1.7000000e+08, 1.5000000e+05, 1.8000000e+05, 3.1500000e+07,
       1.9000000e+06, 2.7500000e+08, 1.9500000e+08, 1.7000000e+05,
       7.5000000e+05, 5.0000000e+04, 9.1000000e+06, 5.3000000e+06,
       2.3000000e+08, 2.5000000e+04, 7.5000000e+04, 5.6000000e+07,
       1.4500000e+07, 7.3000000e+07, 2.7000000e+07, 1.4000000e+07,
       5.6200000e+07, 1.2700000e+08, 1.3000000e+06, 1.5500000e+08,
       1.3500000e+07, 2.0000000e+05, 9.7000000e+07, 2.5000000e+08,
       7.4000000e+07, 9.1600000e+05, 6.2500000e+06, 1.3200000e+08,
       5.2500000e+07, 1.7000000e+06, 2.1500000e+08, 2.8000000e+06,
       9.1300000e+05, 5.6000000e+06, 4.9000000e+06, 9.1000000e+07,
       1.4500000e+08, 1.0600000e+07, 1.3620000e+08, 9.2000000e+06,
       2.4200000e+07, 1.7500000e+07, 3.3000000e+06, 3.4500000e+06,
       1.1500000e+08, 1.6000000e+06, 7.7600000e+07, 4.5000000e+04,
       3.5000000e+04, 4.4500000e+07, 5.8000000e+06, 3.9000000e+07,
       1.5495600e+07, 1.3200000e+07, 5.5000000e+05, 1.2600000e+07,
       8.5000000e+07, 6.9000000e+06, 1.2750000e+08, 9.7000000e+06,
       3.7500000e+07, 2.6300000e+08, 5.9000000e+07, 9.4000000e+06,
       7.9000000e+07, 2.3000000e+06, 5.5000000e+04, 4.6000000e+06,
       2.6000000e+06, 5.7000000e+06, 3.6500000e+08, 3.0000000e+04,
       1.0300000e+08, 2.7500000e+07, 7.8000000e+07, 4.9000000e+07,
       4.2000000e+06, 4.6000000e+07, 4.1000000e+07, 2.7000000e+05,
       5.4000000e+07, 3.4000000e+06, 4.7500000e+06, 7.0000000e+04,
       1.6800000e+07, 3.1400000e+07, 3.2500000e+07, 1.9000000e+05,
       1.2500000e+05, 8.4000000e+05, 6.9000000e+07, 1.9200000e+07,
       1.7700000e+07, 1.9000000e+08, 7.2000000e+06, 1.1200000e+08,
       4.3000000e+06, 2.4000000e+05, 2.1000000e+08, 1.0800000e+07,
       4.0000000e+05, 2.3700000e+08, 2.6000000e+08, 4.8000000e+06,
       2.2000000e+08, 1.8000000e+06, 6.7500000e+07, 1.2000000e+05,
       2.5100000e+07, 1.0700000e+06, 1.1500000e+07, 5.7500000e+07,
       5.4000000e+06, 7.3000000e+06, 2.9000000e+06, 4.3573730e+06,
       2.2500000e+08, 2.0500000e+08, 6.5378900e+06, 9.3000000e+07,
       5.2000000e+07, 1.9100000e+07, 7.6000000e+07, 4.2000000e+04,
       8.6000000e+06, 1.6300000e+08, 6.0720000e+07, 1.1400000e+07,
       2.3600000e+07, 1.9876500e+06, 6.8000000e+06, 8.3000000e+06,
       1.0000000e+04, 1.8500000e+07, 6.7500000e+06, 6.3700000e+07,
       1.3500000e+05, 2.7000000e+04, 3.5000000e+05, 1.9400000e+07,
       8.2500000e+07, 1.8900000e+07, 2.1500000e+07, 1.6000000e+05,
       8.2000000e+07, 4.2000000e+05, 9.3000000e+05, 7.2500000e+06,
       4.4000000e+07, 3.7000000e+06, 7.2500000e+07, 1.3300000e+07,
       9.4000000e+07, 1.1350000e+08, 1.9700000e+07, 3.7900000e+08,
       2.4500000e+06, 1.4900000e+08, 4.0000000e+04, 1.7900000e+08,
       4.4000000e+06, 9.5000000e+05, 2.0700000e+08, 1.3900000e+07,
       1.3750000e+08, 1.1700000e+08, 3.2300000e+05, 7.4000000e+06,
       1.0900000e+08, 7.9000000e+04, 1.1500000e+06, 4.7000000e+06,
       1.0100000e+07, 7.2000000e+07, 5.7000000e+07, 1.0250000e+08,
       5.2000000e+06, 6.6000000e+06, 6.7000000e+07, 9.2000000e+07,
       1.8600000e+08, 1.2800000e+07, 2.6370000e+08, 9.9000000e+06,
       1.1250000e+06, 7.0000000e+03, 1.0300000e+05, 1.3400000e+07,
       7.7500000e+05, 7.7000000e+06, 2.1600000e+07, 2.3800000e+06,
       7.3243106e+07, 1.5000000e+04, 1.4200000e+08, 2.0500000e+07,
       1.5100000e+08, 6.7000000e+06, 1.2300000e+08, 5.0200000e+07,
       1.5500000e+07, 1.0750000e+07, 2.5500000e+07, 8.6000000e+07,
       9.8000000e+06, 3.1000000e+06, 8.2500000e+05, 9.0000000e+03,
       7.8000000e+05, 7.1682975e+07, 6.4000000e+07, 9.8900000e+05,
       1.1000000e+03, 1.3800000e+08, 2.7500000e+06, 2.3000000e+05,
       4.2500000e+07, 8.4700000e+06, 3.8600000e+07, 2.0000000e+04,
       1.5300000e+07, 2.3200000e+08, 5.0000000e+03, 1.3700000e+08,
       9.2500000e+07, 2.5800000e+08, 8.7500000e+07, 1.8975000e+07,
       6.2000000e+06, 1.0500000e+07, 2.8500000e+06, 1.0350000e+07,
       8.1000000e+07, 3.2500000e+06, 7.0702619e+07, 1.2000000e+04,
       8.4000000e+06, 7.3030820e+06, 6.5000000e+04, 1.5600000e+07,
       1.5250000e+07, 1.5150000e+08, 3.5200000e+07, 5.3012938e+07,
       1.3900000e+08, 2.2000000e+06, 5.9000000e+06, 1.0330000e+08,
       2.8500000e+07, 9.8000000e+07, 7.9000000e+06, 1.4200000e+07,
       1.0400000e+07, 8.7000000e+07, 9.7600000e+07, 1.5900000e+08,
       2.0700000e+07, 1.1250000e+07, 1.5750000e+07, 9.3000000e+06,
       1.8200000e+08, 1.4501750e+06, 4.0000000e+08, 6.6000000e+04,
       1.8200000e+07, 6.7972729e+07, 1.7300000e+07, 1.7800000e+06,
       1.6600000e+06, 1.2900000e+08, 3.2000000e+04, 4.1000000e+05])

In the overview I saw that production_budget had quite some null-values 26132 of the 30612, therefore i wanted to double check this if I could get a clearer view on this but I could not. For the null-values I can't take a median or mean, just because there are to many values missing, I will stike with the NaN values.

In [7]:
df['title_clean'] = df['title'].str.strip().str.lower()
df.head()

,year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,opening_weekend,theatre_count,avg run per theatre,runtime,keywords,creative_type,url,title_clean
0,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...,bakha satang
1,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,5486209.0,2433.0,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust,antitrust
2,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos,santitos
3,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...,frank mcklusky c.i.
4,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,12177488.0,2411.0,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...,a walk to remember

Here I normalised the title columm, i made sure that there were only lower cases in the titles and added that to the new colomm title_clean

In [8]:
df['match_key'] = df['title_clean'] + '_' + df['year'].astype(str)
df['match_key'].head()

0           bakha satang_2000
1              antitrust_2001
2               santitos_2000
3    frank mcklusky c.i._2002
4     a walk to remember_2002
Name: match_key, dtype: str

Here I made a match_key so that I eventually can make the new id where I can math on. This because I don't want any letters in my id (primary keys)

In [9]:
df['match_key'].duplicated().sum()

np.int64(107)

I was checking for duplicates in the new colomm and it gave me three, so now im gonna check which ones they are.

In [10]:
print(df['match_key'].isnull().sum())

78

Here I checked all the nullvalues in Match_key to see where the fault is made.

In [11]:
duplicates = df[df['match_key'].notnull() & df['match_key'].duplicated(keep=False)].sort_values('match_key')
duplicates[['title', 'match_key']]

                   title               match_key
191    A Christmas Carol  a christmas carol_2018
338    A Christmas Carol  a christmas carol_2018
27120               Adam               adam_2020
25968               Adam               adam_2020
11826          Aftermath          aftermath_2014
8567           Aftermath          aftermath_2014
9818              Best F             best f_2018
6773              Best F             best f_2018
2330                Blue               blue_2017
2331                Blue               blue_2017
8985                Blue               blue_2017
27032              Clara              clara_2019
23323              Clara              clara_2019
7588            Delirium           delirium_2018
15543           Delirium           delirium_2018
24359          Dreamland          dreamland_2020
27394          Dreamland          dreamland_2020
23880          Dreamland          dreamland_2020
4174         Escape Room        escape room_2017
3584         Escape Room        escape room_2017
1497          First Love         first love_2018
1422          First Love         first love_2018
23496              Greta              greta_2019
28835              Greta              greta_2019
2505      Les affamÃƒÂ©s     les affamãƒâ©s_2018
5826      Les affamÃƒÂ©s     les affamãƒâ©s_2018
29281               Luca               luca_2021
29675               Luca               luca_2021
25493      Made in China      made in china_2019
23305      Made in China      made in china_2019
2773               Money              money_2017
7873               Money              money_2017
2366                Ride               ride_2018
3808                Ride               ride_2018
571                 Ride               ride_2018
27794                Run                run_2020
24226                Run                run_2020
28163          Swan Song          swan song_2021
24937          Swan Song          swan song_2021
21207    The Interpreter    the interpreter_2005
21221    The Interpreter    the interpreter_2005
5780       The Messenger      the messenger_2015
3222       The Messenger      the messenger_2015
8261        The Outsider       the outsider_2018
8259        The Outsider       the outsider_2018
8289   The Space Between  the space between_2017
5410   The Space Between  the space between_2017
19031             Thirst             thirst_2009
18312             Thirst             thirst_2009
26953                Val                val_2021
28431                Val                val_2021
25611            Warning            warning_2021
26437            Warning            warning_2021
21036        White Noise        white noise_2005
22284        White Noise        white noise_2005
15852  Wuthering Heights  wuthering heights_2012
10095  Wuthering Heights  wuthering heights_2012

In [12]:
colliding_keys = df['match_key'][df['match_key'].duplicated(keep=False)]

df.loc[df['match_key'].isin(colliding_keys), 'match_key'] = (
    df.loc[df['match_key'].isin(colliding_keys), 'match_key'] 
    + '_' + df.loc[df['match_key'].isin(colliding_keys), 'runtime'].astype(str)
)

So I'm gonna leave this duplicates, but I need to add something to the name otherwise they will all get matched to the other id's. Therefore I added the runtime, this because in the metaclean data runtime comes up to, this colomm is the most unique and all the runtimes differ from eachother so that is the best one to match on.

In [13]:
df['match_key'].duplicated().sum()

np.int64(82)

So now i added runtime to the name and there are still 82 duplicate values.

In [14]:
print(df['match_key'].duplicated(keep=False).sum())
print(df['match_key'][df['match_key'].duplicated(keep=False)].nunique())

83
0

I did this check to see how many rows there are who are duplicate, and the second one is to see if there are any unique keys who are duplicate.

In [15]:
print(df['match_key'].isnull().sum())

83

In [16]:
print(df[df['match_key'].isnull()][['title', 'title_clean', 'year']])

                     title        title_clean  year
14                     120                NaN  2008
191      A Christmas Carol  a christmas carol  2018
566                      2                NaN  2018
1248                   808                NaN  2016
1571   2016-11-08 00:00:00                NaN  2017
...                    ...                ...   ...
29083                 1921                NaN  2021
29389                  NaN                NaN  2020
29395                 2050                NaN  2020
29863                 1986                NaN  2021
30552                 1982                NaN  2021

[83 rows x 3 columns]

In [18]:
df['title'] = df['title'].astype(str)
df['title'] = df['title'].str.replace(r'\.0$', '', regex=True)

df['title_clean'] = df['title'].str.strip().str.lower()
df['match_key'] = df['title_clean'] + '_' + df['year'].astype(str)

colliding_keys = df['match_key'][df['match_key'].duplicated(keep=False)]
runtime_str = df.loc[df['match_key'].isin(colliding_keys), 'runtime'].fillna('onbekend').astype(str)

df.loc[df['match_key'].isin(colliding_keys), 'match_key'] = (
    df.loc[df['match_key'].isin(colliding_keys), 'match_key'] + '_' + runtime_str
)

print('match_key null:', df['match_key'].isnull().sum())
print('duplicated():', df['match_key'].duplicated().sum())

match_key null: 8
duplicated(): 7

So before I could even build a proper match_key, I noticed that some titles were not being read as text at all. Excel had turned some movie titles into actual numbers or even dates (like "1985" or "2016-11-08"), so when I tried to clean the title column with .str functions, those rows just turned into empty values instead of a proper title. I fixed this by forcing the whole title column to text first with astype(str), and then removed the extra ".0" that showed up on the ones that were read as numbers.

After that I rebuilt title_clean and match_key like before, using title and year. Some of these match_keys were still duplicate, so just like before I need to add something extra to make them unique, otherwise they'll all get matched to the wrong movie later. I used runtime again since that's the most unique column both datasets have and it almost always differs between two movies that share the same title and year.

One thing I ran into is that when runtime was missing for one of the duplicate movies, just adding it straight away actually turned the whole match_key into an empty value instead of keeping it unique, because pandas doesn't turn a missing number into the text "unknown" by itself, it stays empty even after converting to text. So I first filled the missing runtimes with the word "onbekend" before adding it to the match_key, that way even the movies with no runtime info keep a working, unique match_key instead of disappearing into empty values.

In [20]:
df.head()

,year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,opening_weekend,theatre_count,avg run per theatre,runtime,keywords,creative_type,url,title_clean,match_key
0,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...,bakha satang,bakha satang_2000
1,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,5486209.0,2433.0,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust,antitrust,antitrust_2001
2,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos,santitos,santitos_2000
3,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...,frank mcklusky c.i.,frank mcklusky c.i._2002
4,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,12177488.0,2411.0,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...,a walk to remember,a walk to remember_2002

In [21]:
df.to_csv('sales_cleaned.csv', index=False)