In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_excel("metaClean43Brightspace.xlsx")

df.head()

,url,title,studio,rating,runtime,cast,director,genre,summary,awards,metascore,userscore,RelDate
0,https://www.metacritic.com/movie/!women-art-re...,!Women Art Revolution,Hotwire Productions,| Not Rated,83.0,NaN,Lynn Hershman-Leeson,Documentary,NaN,NaN,70,NaN,2011-06-01
1,https://www.metacritic.com/movie/10-cloverfiel...,10 Cloverfield Lane,Paramount Pictures,| PG-13,104.0,"John Gallagher Jr.,John Goodman,Mary Elizabeth...",Dan Trachtenberg,"Action,Sci-Fi,Drama,Mystery,Thriller,Horror","Waking up from a car accident, a young woman (...","#18MostDiscussedMovieof2016 , #1MostSharedMovi...",76,7.7,2016-03-11
2,https://www.metacritic.com/movie/10-items-or-less,10 Items or Less,Click Star,| R,82.0,"Jonah Hill,Morgan Freeman,Paz Vega",Brad Silberling,"Drama,Comedy,Romance",While researching a role as a supermarket mana...,NaN,54,5.8,2006-12-01
3,https://www.metacritic.com/movie/10-years,10 Years,Anchor Bay Entertainment,| R,100.0,"Channing Tatum,Chris Pratt,Jenna Dewan",Jamie Linden,"Drama,Comedy,Romance",NaN,NaN,61,6.9,2012-09-14
4,https://www.metacritic.com/movie/100-bloody-acres,100 Bloody Acres,Music Box Films,| Not Rated,91.0,NaN,Cameron Cairnes,"Horror,Comedy",Reg and Lindsay run an organic fertilizer busi...,NaN,63,7.5,2013-06-28

Here I read the excel file, I firstly imported openpyxl to my environment so I was able to read an excel file. Then I read the excelfile and printed out the first 5 rows.

In [3]:
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 11364 entries, 0 to 11363
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   url        11364 non-null  str
 1   title      11364 non-null  str
 2   studio     11014 non-null  str
 3   rating     10297 non-null  str
 4   runtime    11109 non-null  float64
 5   cast       7662 non-null   str
 6   director   11350 non-null  str
 7   genre      11344 non-null  str
 8   summary    5467 non-null   str
 9   awards     4387 non-null   str
 10  metascore  11364 non-null  int64
 11  userscore  9259 non-null   float64
 12  RelDate    11364 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), str(9)
memory usage: 1.1 MB

url             0
title           0
studio        350
rating       1067
runtime       255
cast         3702
director       14
genre          20
summary      5897
awards       6977
metascore       0
userscore    2105
RelDate         0
dtype: int64

Here I checked the info of the datasets, to see the rows and how many non-null values they have, I also checked the datatypes. I did a double check on how many null values there are in each columm. You can see that url and title got 0 null values, but summary and awards got more than half of the rows for null values.

In [4]:
df['rating'].unique

<bound method Series.unique of 0        | Not Rated
1            | PG-13
2                | R
3                | R
4        | Not Rated
            ...
11359        | PG-13
11360           | PG
11361    | Not Rated
11362           | PG
11363            NaN
Name: rating, Length: 11364, dtype: str>

I saw that the rating columm had a problem that some of them started with '|', now we need to remove that.

In [5]:
df['rating'] = df['rating'].str.strip(' | ').str.strip()
df['rating'].unique

<bound method Series.unique of 0        Not Rated
1            PG-13
2                R
3                R
4        Not Rated
           ...
11359        PG-13
11360           PG
11361    Not Rated
11362           PG
11363          NaN
Name: rating, Length: 11364, dtype: str>

In [6]:
df['awards'] = df['awards'].fillna('none')
df['awards'].unique

<bound method Series.unique of 0                                                     none
1        #18MostDiscussedMovieof2016 , #1MostSharedMovi...
2                                                     none
3                                                     none
4                                                     none
                               ...
11359    #87MostDiscussedMovieof2016 , #80MostSharedMov...
11360                                                 none
11361                                                 none
11362    #80BestMovieof2016 , #11MostDiscussedMovieof20...
11363                                                 none
Name: awards, Length: 11364, dtype: str>

For the nullvalues in the colomm awards we can assume that the movie did not win any awards. Therefore I changed the null value to none.

In [7]:
df['studio'] = df['studio'].str.strip()
df['studio'].value_counts()

studio
IFC Films                                  408
Universal Pictures                         345
Sony Pictures Classics                     344
Warner Bros. Pictures                      302
Netflix                                    301
                                          ...
Manga Video                                  1
Real Women Make Waves                        1
Film Desk, The                               1
myCinema                                     1
20th Century Fox International Classics      1
Name: count, Length: 1118, dtype: int64

I still need to clean the runtime and userscore, I want to use median is that okay? Than there are some rows where director and genre is missing it is not a lot, is it possible to drop them or can we leave them open? There are studios who are written in more ways, what is the best way to clean this?

In [8]:
df['runtime'] = df['runtime'].fillna(df['runtime'].median())
df['userscore'] = df['userscore'].fillna(df['userscore'].median())

Here I filled the nullvalues of runtime and metascore with the median.

In [9]:
df[df['genre'].isnull()]

,url,title,studio,rating,runtime,cast,director,genre,summary,awards,metascore,userscore,RelDate
1798,https://www.metacritic.com/movie/chalk-2000,Chalk,Tenderloin Action Group,NaN,134.0,NaN,Rob Nilsson,NaN,This gritty drama focuses on the misfits who h...,none,57,6.7,2000-08-25
1886,https://www.metacritic.com/movie/chop-shop,Chop Shop,Koch Lorber Films,Unrated,84.0,NaN,Ramin Bahrani,NaN,NaN,#18BestMovieof2008,83,7.7,2008-02-27
1968,https://www.metacritic.com/movie/closed-curtain,Closed Curtain,Variance Films,Not Rated,106.0,NaN,Jafar Panahi,NaN,NaN,#50BestMovieof2014,81,5.1,2014-07-09
2300,https://www.metacritic.com/movie/daydream-beli...,Daydream Believer,Film Threat DVD,NaN,79.0,NaN,Debra Eisenstadt,NaN,"An edgy, contemporary take on an age-old story...",none,53,6.7,2002-09-25
2502,https://www.metacritic.com/movie/djomeh,Djomeh,New Yorker Films,NaN,94.0,"Jalil Nazari,Rashid Akbari",Hassan Yektapanah,NaN,"Djomeh, a shy young Afghani working in a remot...",#52BestMovieof2001,76,6.7,2001-09-05
2969,https://www.metacritic.com/movie/farewell-amor,Farewell Amor,IFC Films,NR,101.0,NaN,NaN,NaN,NaN,none,75,6.7,2020-12-11
4215,https://www.metacritic.com/movie/in-heaven-und...,In Heaven Underground: The Weissensee Jewish C...,Seventh Art Releasing,Not Rated,90.0,NaN,NaN,NaN,NaN,none,67,6.7,2011-11-18
4844,https://www.metacritic.com/movie/langrishe-go-...,Langrishe Go Down,Castle Hill Productions,NaN,105.0,NaN,David Hugh Jones,NaN,The theatrical release of a 1978 BBC film star...,none,59,4.0,2002-07-17
4957,https://www.metacritic.com/movie/les-miserable...,Les MisÃ©rables,Amazon Studios,Not Rated,102.0,"Alexis Manenti,Damien Bonnard,Djibril Zonga,Je...",Ladj Ly,NaN,NaN,#80BestMovieof2020,78,6.6,2020-01-10
4986,https://www.metacritic.com/movie/liberte,LibertÃ©,Cinema Guild,Not Rated,132.0,"Baptiste Pinteaux,Catalin Jugravu,Francesc Dar...",Albert Serra,NaN,NaN,none,51,6.7,2020-05-01
6153,https://www.metacritic.com/movie/off-the-hook,Off the Hook,Sharpshooter Pictures,PG,108.0,"Jamal Mackey,Walter Velasquez",Adam Watstein,NaN,The true story of two friends who live in the ...,none,52,6.7,2001-07-06
7244,https://www.metacritic.com/movie/scumrock,Scumrock,Complex,NaN,79.0,NaN,Jon Moritsugu,NaN,Undergound director Jon Moritsugu examines the...,none,42,6.7,2004-11-05
7899,https://www.metacritic.com/movie/such-a-long-j...,Such a Long Journey,Shooting Gallery,NaN,113.0,NaN,Sturla Gunnarsson,NaN,NaN,#62BestMovieof2000,74,7.0,2000-03-24
8649,https://www.metacritic.com/movie/the-dogwalker,The Dogwalker,Truly Indie,NaN,99.0,NaN,Jacques Thelemaque,NaN,NaN,none,45,8.3,2006-08-25
8815,https://www.metacritic.com/movie/the-freebie,The Freebie,Phase 4 Films,R,78.0,NaN,Katie Aselton,NaN,A young couple decides to give each other a ni...,none,54,6.7,2010-09-17
9946,https://www.metacritic.com/movie/the-tavern,The Tavern,Castle Hill Productions,NaN,95.0,NaN,Walter Foote,NaN,Best friends Ronnie and Dave struggle to run a...,none,57,6.7,2000-09-22
10210,https://www.metacritic.com/movie/the-year-of-t...,The Year of the Everlasting Storm,Neon,Not Rated,115.0,NaN,Anthony Chen,NaN,Featuring seven stories from seven auteurs fro...,none,72,6.7,2021-09-03
10267,https://www.metacritic.com/movie/thirteen-2000,Thirteen,E.D. Distribution,NaN,87.0,NaN,David D. Williams,NaN,The quasi-documentary story of a year in the l...,#29BestMovieof2000,78,8.4,2000-06-02
10473,https://www.metacritic.com/movie/treeless-moun...,Treeless Mountain,Oscilloscope Pictures,Not Rated,89.0,NaN,So Yong Kim,NaN,NaN,#73BestMovieof2009,75,7.6,2009-04-22
11144,https://www.metacritic.com/movie/winter-in-the...,Winter in the Blood,Kino Lorber,Not Rated,105.0,NaN,Alex Smith,NaN,Virgil First Raise (Chaske Spencer) embarks on...,none,52,6.7,2014-08-20

Here we took a look at all the rows who had a nullvalue in genre, we did this to see if the movies are important to keep.

In [10]:
df[df['director'].isnull()]

,url,title,studio,rating,runtime,cast,director,genre,summary,awards,metascore,userscore,RelDate
1578,https://www.metacritic.com/movie/brothers-in-arms,Brothers in Arms,First Run Features,Unrated,68.0,NaN,NaN,War,This documentary focuses on the crew of Patrol...,none,48,6.7,2004-08-27
2969,https://www.metacritic.com/movie/farewell-amor,Farewell Amor,IFC Films,NR,101.0,NaN,NaN,NaN,NaN,none,75,6.7,2020-12-11
3364,https://www.metacritic.com/movie/generation-war,Generation War,Music Box Films,Not Rated,270.0,NaN,NaN,"Drama,History,War",NaN,none,57,7.4,2014-01-15
3759,https://www.metacritic.com/movie/head-games,Head Games,Variance Films,PG--13,100.0,NaN,NaN,Documentary,NaN,none,69,6.7,2012-09-21
4215,https://www.metacritic.com/movie/in-heaven-und...,In Heaven Underground: The Weissensee Jewish C...,Seventh Art Releasing,Not Rated,90.0,NaN,NaN,NaN,NaN,none,67,6.7,2011-11-18
4331,https://www.metacritic.com/movie/into-eternity,Into Eternity,International Film Circuit,Unrated,75.0,NaN,NaN,Documentary,NaN,none,68,6.7,2011-02-02
5253,https://www.metacritic.com/movie/lynch,Lynch,Absurda,Not Rated,84.0,NaN,NaN,Documentary,NaN,none,67,8.6,2007-10-26
6668,https://www.metacritic.com/movie/price-check,Price Check,IFC Films,Not Rated,92.0,NaN,NaN,"Drama,Comedy",A mid-level exec in a supermarket chain (Mabiu...,none,67,6.5,2012-11-16
6882,https://www.metacritic.com/movie/red-hill,Red Hill,Strand Releasing,R,95.0,"Ryan Kwanten,Steve Bisley,Tommy Lewis",NaN,"Thriller,Crime,Western",NaN,none,62,6.7,2010-11-05
7311,https://www.metacritic.com/movie/seven-days-in...,Seven Days in Utopia,Utopia Pictures,G,120.0,NaN,NaN,"Drama,Sport",NaN,none,37,5.8,2011-09-02
8206,https://www.metacritic.com/movie/the-animation...,The Animation Show 2005,The Animation Show,Not Rated,85.0,NaN,NaN,Animation,A collection of the world's best animated shor...,#63BestMovieof2005,76,7.5,2005-02-18
8650,https://www.metacritic.com/movie/the-donut-king,The Donut King,Greenwich Entertainment,NR,98.0,NaN,NaN,Documentary,NaN,none,69,6.7,2020-10-30
9411,https://www.metacritic.com/movie/the-mighty-macs,The Mighty Macs,Ocean Avenue Entertainment,G,102.0,NaN,NaN,"Action,Drama,Sport",NaN,none,49,6.2,2011-10-21
9579,https://www.metacritic.com/movie/the-penguin-k...,Adventures of the Penguin King,nWave Pictures,PG,78.0,NaN,NaN,"Adventure,Drama,Family",This documentary follows a young male King Pen...,none,35,6.7,2013-12-06

Now we did the same for directors.

In [11]:
df = df.dropna(subset=['director', 'genre'])

Here I dropped the rows that have nullvalues for director and genre.

In [12]:
df['rating'] = df['rating'].replace({'PG--13': 'PG-13', 'PG-13`': 'PG-13'})

There were still some values of rating with a double -- and one with some with a '`' I changed these one so everyone of them were the same value.

In [13]:
df['title_clean'] = df['title'].str.strip().str.lower()
df.head()

,url,title,studio,rating,runtime,cast,director,genre,summary,awards,metascore,userscore,RelDate,title_clean
0,https://www.metacritic.com/movie/!women-art-re...,!Women Art Revolution,Hotwire Productions,Not Rated,83.0,NaN,Lynn Hershman-Leeson,Documentary,NaN,none,70,6.7,2011-06-01,!women art revolution
1,https://www.metacritic.com/movie/10-cloverfiel...,10 Cloverfield Lane,Paramount Pictures,PG-13,104.0,"John Gallagher Jr.,John Goodman,Mary Elizabeth...",Dan Trachtenberg,"Action,Sci-Fi,Drama,Mystery,Thriller,Horror","Waking up from a car accident, a young woman (...","#18MostDiscussedMovieof2016 , #1MostSharedMovi...",76,7.7,2016-03-11,10 cloverfield lane
2,https://www.metacritic.com/movie/10-items-or-less,10 Items or Less,Click Star,R,82.0,"Jonah Hill,Morgan Freeman,Paz Vega",Brad Silberling,"Drama,Comedy,Romance",While researching a role as a supermarket mana...,none,54,5.8,2006-12-01,10 items or less
3,https://www.metacritic.com/movie/10-years,10 Years,Anchor Bay Entertainment,R,100.0,"Channing Tatum,Chris Pratt,Jenna Dewan",Jamie Linden,"Drama,Comedy,Romance",NaN,none,61,6.9,2012-09-14,10 years
4,https://www.metacritic.com/movie/100-bloody-acres,100 Bloody Acres,Music Box Films,Not Rated,91.0,NaN,Cameron Cairnes,"Horror,Comedy",Reg and Lindsay run an organic fertilizer busi...,none,63,7.5,2013-06-28,100 bloody acres

Here I normalised the title columm, i made sure that there were only lower cases in the titles and added that to the new colomm title_clean

In [14]:
df['match_key'] = df['title_clean'] + '_' + df['RelDate'].dt.year.astype(str)
df['match_key'].head()

0    !women art revolution_2011
1      10 cloverfield lane_2016
2         10 items or less_2006
3                 10 years_2012
4         100 bloody acres_2013
Name: match_key, dtype: str

Here I made a match_key so that I eventually can make the new id where I can math on. This because I don't want any letters in my id (primary keys)

In [15]:
df['match_key'].duplicated().sum()

np.int64(3)

I was checking for duplicates in the new colomm and it gave me three, so now im gonna check which ones they are.

In [16]:
double_keys = df[df['match_key'].duplicated(keep=False)]
double_keys.sort_values('match_key')

,url,title,studio,rating,runtime,cast,director,genre,summary,awards,metascore,userscore,RelDate,title_clean,match_key
2625,https://www.metacritic.com/movie/dreamland-2019,Dreamland,Paramount Pictures,R,98.0,"Darby Camp,Finn Cole,Garrett Hedlund,Ginger T....",Miles Joris-Peyrafitte,"Drama,Thriller",NaN,none,57,5.6,2020-11-13,dreamland,dreamland_2020
2626,https://www.metacritic.com/movie/dreamland-2020,Dreamland,Uncork'd Entertainment,TV-MA,92.0,"Astrid Roos,Barbara Hellemans,DaphnÃ© Huynh,Gu...",Bruce McDonald,"Fantasy,Horror,Comedy,Crime",On the night of the strangest weddings in hist...,none,50,6.7,2020-06-05,dreamland,dreamland_2020
7975,https://www.metacritic.com/movie/swan-song,Swan Song,Magnolia Pictures,Not Rated,105.0,"Annie Kitral,Dave Sorboro,Eric Eisenbrey,Ira H...",Todd Stephens,Drama,NaN,none,66,6.8,2021-08-06,swan song,swan song_2021
7976,https://www.metacritic.com/movie/swan-song-2021,Swan Song,Apple TV+,R,116.0,"Adam Beach,Awkwafina,Dax Rey,Glenn Close,Jayr ...",Benjamin Cleary,"Sci-Fi,Drama","In the near future, Cameron Turner (Mahershala...",none,66,7.0,2021-12-17,swan song,swan song_2021
9058,https://www.metacritic.com/movie/the-hunter,The Hunter,Olive Films,Not Rated,90.0,NaN,Rafi Pitts,Thriller,NaN,#66BestMovieof2012,76,7.1,2012-01-04,the hunter,the hunter_2012
9059,https://www.metacritic.com/movie/the-hunter-2012,The Hunter,Magnolia Pictures,R,100.0,"Jacek Koman,Morgana Davies,Sam Neill,Willem Dafoe",Daniel Nettheim,"Adventure,Drama",NaN,none,63,7.1,2012-04-06,the hunter,the hunter_2012

Here I did the extra check to see if the duplicates really are the same movies. As you can see it definently are different movies, with different studios,casts and directors etc. So I'm gonna leave this duplicates, but I need to add something to them otherwise they will all get matched to the other id's. Therefore I'm gonna add the runtime, this because in the sales data runtime comes up to, this colomm is the most unique and all the runtimes differ from eachother so that is the best one to match on.

In [17]:
colliding_keys = df['match_key'][df['match_key'].duplicated(keep=False)]

df.loc[df['match_key'].isin(colliding_keys), 'match_key'] = (
    df.loc[df['match_key'].isin(colliding_keys), 'match_key'] 
+ '_' + df.loc[df['match_key'].isin(colliding_keys), 'runtime'].astype(str)
)

In [18]:
df['match_key'].duplicated().sum()

np.int64(0)

So now i added the runtime to the duplicate values and there are 0 nullvalues left.

In [20]:
df.to_csv('metaclean_cleaned.csv', index=False)